### ISSUE TITLE
Option to not draw a diff image if they are the same

### ISSUE THREAD

**Issue by tinganho** [uber/image-diff#28] opened 2015-07-20 06:29 UTC
Title says it all

**Comment by twolfson** [comment] 2015-07-20 06:42
This is a duplicate of #27. The reason is our underlying engine (ImageMagick) has no options to perform this action. In the future, please be sure to search issues (both opened and closed) to prevent using unnecessary time.

@mlmorg Can we please close this issue?

**Comment by tinganho** [comment] 2015-07-20 06:47
@twolfson oops sorry for duplication.

**Closed** 2015-07-20 06:47 UTC
